### PR TITLE
BUG Remove broken search filter

### PR DESCRIPTION
**Pull request by maxime-rainville**
This broken search filter blocks you from adding entries to the the past employees table on the Company Gridfield.

### CODE REVIEW

**Comment by chillu** [comment]
This looks like a legit filter to me. If it breaks functionality, we should probably track down why that is?

**Comment by maxime-rainville** [comment]
Company is a `HasOne` relation. What are you meant to exactly match in this scenario?

**Comment by chillu** [comment]
I think changing it to `CompanyID` will work, see `DBForeignKey->scaffoldSearchField()`. I've just checked `DataObject->scaffoldSearchFields()`, it uses `$this->relObject($fieldName)` which only works with fields, not relationships. We could add that feature (`Company` implies `CompanyID`), but that's scope creep - I'd prefer you change this to `CompanyID` rather than remove it, since it's testing an important use case.

**Comment by maxime-rainville** [comment]
There's already a field for CompanyID that had a silly `LessThanFilter`. Decided to remove that one as well and scaffold a DropdownField for Company instead. 

I feel this provides a more useful testing scenario as it includes a manually created field as well as the scaffolded ones.

**Comment by maxime-rainville** [comment]
People were not interested.

**Pull request closed without merging**
